[dev]
framework = "#static"
command = "npx @11ty/eleventy --input=src --quiet --watch"

[build]
command = "npx @11ty/eleventy --input=src"
publish = "dist"

[[edge_functions]]
function = "eleventy-edge"
path = "/"

[[redirects]]
from = "/"
to = "/.netlify/functions/nasa"
status = 200
force = true
_generated_by_eleventy_serverless = "nasa"
